[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture "

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
